### ISSUE TITLE
TypeError when modifying custom membership

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#158]
When modifying a customly added group membership that has a begin date of `None`, which is valid, although not possible to create via UI, then changing this membership results in

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/pycroft/web/blueprints/user/__init__.py", line 312, in end_membership
    membership.disable()
  File "/pycroft/pycroft/model/user.py", line 437, in disable
    if self.begins_at > now:
TypeError: unorderable types: NoneType() > datetime.datetime()
```

**Comment by ibot3** [comment]
Should it be possible to edit/add groups with no begin date?
Because editing such a membership will require you to enter a begin date.

**Comment by lukasjuhrich** [comment]
It is possible with respect to the data model, but the UI does not support adding such a membership, because there isn't really a need to. Another example is for instance that while switches can be deleted from the database, it makes no sense to add a button for that in the UI.
