### ISSUE TITLE
Empty mail address field throws AttributeError

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#420]
Trying to edit a debitorennummer, I submitted the user_edit form in the following state:
- Old Name
- Empty email
- Ticked checkbox „email redirection“ (note I dit not _explicitly_ tick that box)
- Old birthdate
- New debitorennummer (previously None)

I got a 500, and the logs reported:

```
Traceback (most recent call last):                                                                            
  File "/opt/pycroft/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app                   
    response = self.full_dispatch_request()                                                                   
  File "/opt/pycroft/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)                                                                        
  File "/opt/pycroft/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)                                                                                
  File "/opt/pycroft/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)                                                                          
  File "/opt/pycroft/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise                  
    raise value                                                                                               
  File "/opt/pycroft/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()                                                                              
  File "/opt/pycroft/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)                                                
  File "/opt/pycroft/venv/lib/python3.7/site-packages/web/blueprints/user/__init__.py", line 845, in edit_user
    form.email_forwarded.data, current_user)                                                                  
  File "/opt/pycroft/venv/lib/python3.7/site-packages/pycroft/model/session.py", line 45, in with_transaction 
    rv = wrapped(*args, **kwargs)                                                                             
  File "/opt/pycroft/venv/lib/python3.7/site-packages/pycroft/lib/user.py", line 533, in edit_email           
    email = email.lower()                                                                                     
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by lukasjuhrich** [comment]
Update: this _also_ occurs when explicitly removing the „add email redirection“ tick
